// Only these types are handled by the compiler. In case of filetype other, the file is just copied
module.exports = {
    '.scss':    'stylesheet',
    '.less':    'stylesheet',
    '.sass':    'stylesheet',
    '.styl':    'stylesheet',
    '.stylus':  'stylesheet',
    '.css':     'stylesheet',
    '.ts':      'javascript',
    '.js':      'javascript',
    '.coffee':  'javascript',
    '.vue':     'javascript',
    '.pug':     'page',
    '.jade':    'page',
    '.html':    'page',
    '.htm':     'page',
    '.md':      'page',
    '.jpeg':    'image',
    '.jpg':     'image',
    '.svg':     'image',
    '.png':     'image',
    '.gif':     'image',
    '.pdf':     'other',
    '.txt':     'other',
    '.json':    'other',
    '.csv':     'other',
    '.xml':     'other'
}